# https://taskfile.dev

version: "3"

dotenv: [".env"]

env:
  PROJECT_ROOT: "./"

tasks:
  default:
    cmds:
      - task: dev
  dev:
    cmds:
      - wails dev
  build:
    cmds:
      - task: build-linux
      - task: build-darwin
      - task: build-windows
  build-linux:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - wails build -platform "linux/amd64" -o boold_{{.APP_VERSION}}_linux-amd64 -tags webkit2_41
  build-darwin:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - wails build -platform "darwin/amd64" -o boold_{{.APP_VERSION}}_darwin-amd64.dmg
  build-windows:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - wails build -platform "windows/amd64" -upx -nsis -o boold_{{.APP_VERSION}}_windows-amd64.exe
  frontend:fmt:
    dir: "frontend"
    cmds:
      - bunx oxfmt
  frontend:fmt-check:
    dir: "frontend"
    cmds:
      - bunx oxfmt --check
  fmt-all:
    cmds:
      - task: frontend:fmt
      - task: backend:fmt
  backend:fmt:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - echo "$(pwd)"
      - go fmt ./...
  install-hooks:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - task: install-pre-commit-hook
  uninstall-hooks:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - task: uninstall-pre-commit-hook
  install-pre-commit-hook:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - cp ./scripts/run-pre-commit-hook.sh .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "pre-commit hook installed!"
    silent: true
  uninstall-pre-commit-hook:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - rm -f .git/hooks/pre-commit
      - echo "pre-commit hook uninstalled!"
    silent: true
  reset-hooks:
    dir: "{{.PROJECT_ROOT}}"
    cmds:
      - rm -f .git/hooks/pre-commit
      # - rm -f .git/hooks/pre-push
      # - rm -f .git/hooks/commit-msg
      - echo "all git hooks removed!"
    silent: true
